### ISSUE TITLE
希望能支持单一数据文件geosite.dat

### ISSUE THREAD

**Issue by lededev** [zfl9/chinadns-ng#102]
[Loyalsoldier](https://github.com/Loyalsoldier/v2ray-rules-dat)的geosite.dat是v2ray官网的增强版，已经获得8K+的Star。
用语法 geosite:cn geosote:gfw 可以完全替代 --gfwlist-file -chnlist-file 这两份文件。
很多硬路由的闪存不大，用了v2ray xray之后，将持续更新geosite.dat文件到最新数据。
为了使用chinadns-ng，继续下载上述两份文件到本不充足的闪存空间内，其实是冗余数据，所以希望chinadns-ng也能支持geosite.dat实现单一数据源分流。

**Comment by zfl9** [comment]
gfwlist.txt和chnlist.txt两个文件加起来，大约不到1mb的大小。
我认为这不算太占用磁盘空间，我不知道你说的闪存不大，具体是还剩多少空间可用呢？
不是很熟悉geosite.dat的文件格式(文本还是二进制)，与之前的"域名后缀"格式是否相近，解析是否方便。
> 目前时间和精力非常有限(维护github全靠"爱")，很多issue和需求都是一拖再拖，没时间去弄，996害人。。

**Comment by lededev** [comment]
geosite.dat的文件格式是google的proto buffer的二进制格式，可以用C语言版本的公共库[[libprotobuf-c](https://openwrt.org/packages/pkgdata/libprotobuf-c)](https://github.com/protobuf-c/protobuf-c)进行读取。
而geosite.proto则是它的结构化定义，在[v2ray官网](https://github.com/v2fly/v2ray-core/blob/master/app/router/routercommon/common.proto)可以取得。

另外，开了这个issue之后，我又发现了另一个dns缓冲程序[MosDns-CN](https://github.com/IrineSistiana/mosdns-cn)，是go语言编写的，正是用geosite.dat进行分流的，但缺点是go语言编译的目标文件很大，硬路由还是用C语言的执行程序更适合。
```
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - "ext:/usr/share/v2ray/geosite.dat:geolocation-!cn"

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - "ext:/usr/share/v2ray/geoip.dat:cn"
```
